### ISSUE TITLE
Crashes with Sodium latest commit

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [FlashyReese/reeses-sodium-options#1]
Latest commit of reeses-sodium-options crashes with latest commit of sodium when opening the video settings menu.
[Crash Report](https://gist.github.com/DragonEggBedrockBreaking/4b4f9b8d20aece23906828d03badc12a)

**Comment by FlashyReese** [comment]
It's borked with the GUI fixes merge

**Comment by DragonEggBedrockBreaking** [comment]
Fixed in the next-compat branch
