### ISSUE TITLE
Upstream (parts of) it

### ISSUE THREAD

**Issue by Madis0** [FlashyReese/reeses-sodium-options#10]
Just made an issue here to remind you of this (even though we discussed on Discord earlier) that you can upstream parts of the mod to Sodium, currently Jelly is looking for the scrolling feature: https://github.com/CaffeineMC/sodium-fabric/issues/867

**Comment by FlashyReese** [comment]
I think don't my current implementation of the menu is the right fit/way for Sodium. In terms of code quality, my current implementation is more of a UI library with hacky ways of implementing such features.
