### ISSUE TITLE
Crash immediately after pressing options button

### ISSUE THREAD

**Issue by Rafii2198** [FlashyReese/reeses-sodium-options#101]
The game just crashes when trying to open options menu
Crash Log https://mclo.gs/tfbAu0s

**Comment by FlashyReese** [comment]
Update to https://modrinth.com/mod/reeses-sodium-options/version/mc1.21.1-1.8.0-beta.2+fabric

**Comment by Jepl4r** [comment]
> Update to https://modrinth.com/mod/reeses-sodium-options/version/mc1.21.1-1.8.0-beta.2+fabric

I have the same issue. Using the version you suggested results in a crash too.

[Crash Log Minecraft MacOS.txt](https://github.com/user-attachments/files/16840106/Crash.Log.Minecraft.MacOS.txt)

**Comment by Rafii2198** [comment]
I am also on that version already, or at least this is what Fabric reports `reeses-sodium-options: Reese's Sodium Options 1.8.0-beta.2+mc1.21.1`

**Comment by FlashyReese** [comment]
> > Update to https://modrinth.com/mod/reeses-sodium-options/version/mc1.21.1-1.8.0-beta.2+fabric
> 
> I have the same issue. Using the version you suggested results in a crash too.
> 
> [Crash Log Minecraft MacOS.txt](https://github.com/user-attachments/files/16840106/Crash.Log.Minecraft.MacOS.txt)

Yours is caused by Controlify mixing into an old version of our mod.

**Comment by FlashyReese** [comment]
> I am also on that version already, or at least this is what Fabric reports `reeses-sodium-options: Reese's Sodium Options 1.8.0-beta.2+mc1.21.1`

![image](https://github.com/user-attachments/assets/bc9867ba-bbac-47e8-8db2-437e8e342888)
Your log says otherwise, unless you are also using Controlify.

**Comment by Rafii2198** [comment]
Ah, my bad, I know what happened, I did have Controlify and I tried downgrading your mod first to see if it is version related, but it kept crashing, and so I tried disabling everything but those 2 mods while keeping the second to latest version. My apologies, I should do more extensive testing.

**Comment by Jepl4r** [comment]
> > > Update to https://modrinth.com/mod/reeses-sodium-options/version/mc1.21.1-1.8.0-beta.2+fabric
> > 
> > 
> > I have the same issue. Using the version you suggested results in a crash too.
> > [Crash Log Minecraft MacOS.txt](https://github.com/user-attachments/files/16840106/Crash.Log.Minecraft.MacOS.txt)
> 
> Your is caused by Controlify mixing into an old version of our mod.

Ah ok, I'm gonna report the issue to the Controlify dev. Thanks.

**Comment by JaredRichardWilliam** [comment]
https://github.com/isXander/Controlify/issues/407#issue-2501550385
