### ISSUE TITLE
Crash On sodium beta 2

### ISSUE THREAD

**Issue by ShadowTigerCool** [FlashyReese/reeses-sodium-options#104]
Clicking on video settings, cause a instant crash

[crash-2024-09-15_14.56.39-client.txt](https://github.com/user-attachments/files/17007054/crash-2024-09-15_14.56.39-client.txt)
 
https://pastebin.com/B6W5zuAr

**Comment by FlashyReese** [comment]
See new version at https://modrinth.com/mod/reeses-sodium-options/versions
