### ISSUE TITLE
Crash when typing F

### ISSUE THREAD

**Issue by In0ctScuirrle** [FlashyReese/reeses-sodium-options#108]
You get the crash if you type F doesn't matter the case it just crashes when you type f. Mate what kind of String Parser did you make?

[crash-2024-09-18_18.00.35-client.txt](https://github.com/user-attachments/files/17046816/crash-2024-09-18_18.00.35-client.txt)

[latest.log](https://github.com/user-attachments/files/17046821/latest.log)

**Comment by FlashyReese** [comment]
Duplicate of #105
