### ISSUE TITLE
Crash when opening video settings

### ISSUE THREAD

**Issue by MarkHarrisMedia** [FlashyReese/reeses-sodium-options#109]
![image](https://github.com/user-attachments/assets/99217b8f-e1d4-487c-8b06-f846944bcdce)

Crash when opening video settings every time.

Just updated sodium and reese's sodium options on my 1.21.1 client via MultiMC and, while it works. It crashes every time I go to open video settings.

**Comment by MarkHarrisMedia** [comment]
I removed Reese's sodium extras mod (reeses-sodium-options-fabric-1.8.0-beta.3+mc1.21.1.jar) and it fixed the problem.

I can now access video settings without game crashing. 
Maybe I will try a previous version tomorrow. I will keep you updated.

Running with
sodium-fabric-0.6.0-beta.2+mc1.21.1
sodium-extra-fabric-0.6.0-beta.3+mc1.21.1

**Comment by FlashyReese** [comment]
I need the rest of the log

**Comment by MarkHarrisMedia** [comment]
> I need the rest of the log

Please visit this post I made on sodium GitHub first before I realized it was Reese's sodium options causing the crash.

https://github.com/CaffeineMC/sodium-fabric/issues/2765

**Comment by FlashyReese** [comment]
Controlify is at fault here. They are modifying our mod but those files aren't there anymore.
