### ISSUE TITLE
keep getting crash when opening the video settings (in my modpack) (CLIENT-SIDE-MODPACK) (not on curseforge as a modpack yet ): )

### ISSUE THREAD

**Issue by PROGAMER1500** [FlashyReese/reeses-sodium-options#11]

**Comment by PROGAMER1500** [comment]
here is the crash report https://bytebin.lucko.me/QFZ15mq8DU

**Comment by PROGAMER1500** [comment]
url supported by (not enough crashes)

**Comment by FlashyReese** [comment]
Try removing `betteruiscale` mod to see if it still occurs, also I don't think I'm at fault here looking at the crash report.
