### ISSUE TITLE
Game crashes when opening the settings

### ISSUE THREAD

**Issue by 12Mosch** [FlashyReese/reeses-sodium-options#110]
Game crashes when opening the settings ingame with mc1.21.1-1.8.0-beta.4+fabric

[crash-2024-09-21_10.28.57-client.txt](https://github.com/user-attachments/files/17083431/crash-2024-09-21_10.28.57-client.txt)
[latest.log](https://github.com/user-attachments/files/17083440/latest.log)

**Comment by sh2kcs** [comment]
I have the same thing

**Comment by FlashyReese** [comment]
https://github.com/FlashyReese/reeses-sodium-options/issues/109#issuecomment-2361457957
