### ISSUE TITLE
[Request] Compatibility with Embeddium

### ISSUE THREAD

**Issue by hideki2k02** [FlashyReese/reeses-sodium-options#115]
Hello, any plans on supporting Embeddium? It is required on my pack due to Sodium being incompatible with a fews mods.

**Comment by FlashyReese** [comment]
They already use my code I don't see why I should.

**Comment by FlashyReese** [comment]
![image](https://github.com/user-attachments/assets/e761ebc1-9da0-43f7-8756-94c474c98792)

**Comment by hideki2k02** [comment]
Thanks for the fast reply! I guess I should get in contact with Sodium Extras developer then.
