### ISSUE TITLE
1.8.0-beta.4 crash when opening video settings 

### ISSUE THREAD

**Issue by pieryo** [FlashyReese/reeses-sodium-options#116]
I figured out that its trying to do something with (FlatButtonWidget), but it cant because it doesn't exist.  I'm not very good at coding so I'm a little clueless but here's my crash-report. 

[crash-2024-10-06_21.54.59-client.txt](https://github.com/user-attachments/files/17273229/crash-2024-10-06_21.54.59-client.txt)

**Comment by pieryo** [comment]
misclick

**Comment by GalaxyStudiosG** [comment]
I am having the same issue, here is my log on mclo.gs.
https://mclo.gs/IjowaV3

**Comment by FlashyReese** [comment]
Caused by https://github.com/FlashyReese/reeses-sodium-options/issues/102, this needs to be fixed on Controlify's end.
