### ISSUE TITLE
game crashes when using search function

### ISSUE THREAD

**Issue by nenamoree9** [FlashyReese/reeses-sodium-options#121]
So i was trying to use the search function but the game crashes.

My version is 1.21
Reeses sodium options version is: 1.8.0 Beta 3
Fabric version: 0.16.9-1.21.1

Steps to replicate:
1. Go to video settings
2. Click search
3. Type stuff

My crash report:
[crash-2024-11-18_20.06.16-client.txt](https://github.com/user-attachments/files/17809186/crash-2024-11-18_20.06.16-client.txt)

**Comment by FlashyReese** [comment]
This was fixed in beta 4
