### ISSUE TITLE
"Shader Packs..." button doesn't work on 1.21.4

### ISSUE THREAD

**Issue by Excederus** [FlashyReese/reeses-sodium-options#125]
Using the current latest version of Sodium, Iris & Reese's Sodium Options causes the "Shader Packs..." button in the video settings menu to not work. Nothing happens when clicking it.

Sodium version: mc1.21.4-0.6.2-fabric
Iris version: 1.8.3+1.21.4-fabric
Reese's Sodium Options version: mc1.21.4-1.8.1+fabric

No other mods installed

**Comment by Alastair-Grey** [comment]
You can try to click on the top of "k" in "Shader Packs...".It works for me.

**Comment by ghost** [comment]
seems that this issue happens to me. robotkoer told me to edit or delete sodium config file and retry, so you can try that, Excederus

**Comment by Madis0** [comment]
To be clear, the button only stops working when you hide the Sodium donate button. If it's visible (as it is on default Sodium config file), then it works.

**Comment by GIMMI42PIASTRATO** [comment]
> To be clear, the button only stops working when you hide the Sodium donate button. If it's visible (as it is on default Sodium config file), then it works.

How do I make the donation button visible without deleting the sodium configuration files?

**Comment by GIMMI42PIASTRATO** [comment]
> How do I make the donation button visible without deleting the sodium configuration files?

I solved it: Go to the instance folder > config > sodium-options.json
Set `"has_cleared_donation_button"` to false

```json
"notifications": {
    "has_cleared_donation_button": false
}
```

**Comment by salpelter** [comment]
Thank you @Kotiya-Sanae and @GIMMI42PIASTRATO, you're lifesavers!
Meanwhile, I can confirm that this issue is still relevant.
