### ISSUE TITLE
"Performance" Tab of Sodium's video settings is missing in Reese's sodium options 1.2.2 for 1.17

### ISSUE THREAD

**Issue by Jukitsu** [FlashyReese/reeses-sodium-options#23]
This is without Reese's Sodium options:
![image](https://user-images.githubusercontent.com/84381972/144683271-032d347d-fe40-4528-83bd-50bfa207904c.png)

This is with Reese's Sodium options:
![image](https://user-images.githubusercontent.com/84381972/144683086-6c19d4d2-7cbb-404d-81f0-771f4a57d7c8.png)

As you can see the "Performance" Tab is missing.

**Comment by FlashyReese** [comment]
This has been fixed already and released. I may have accidentally removed from GitHub releases but it can be found [here on curseforge](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options/files/3536465) or GitHub releases I've just re-released it
