### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by itsdinkd** [FlashyReese/reeses-sodium-options#24]
on latest 1.18 version, when game loads for first time and GUI scale is at auto, you cannot press the "apply" button due to the tooltip popups interfering  by overlaying with it.

**Comment by emielderckx** [comment]
I can confirm this, it's impossible to change GUI scale.

![7W54EakHb4](https://user-images.githubusercontent.com/35953244/146685916-15064106-65d8-4272-96c9-187552dcd27e.gif)

**Comment by FlashyReese** [comment]
Hello, I have made a temporary hot fix for it. Can you guys try this build out? https://github.com/FlashyReese/reeses-sodium-options/suites/4625694998/artifacts/125217607

**Comment by emielderckx** [comment]
Yep that one works good

**Comment by FlashyReese** [comment]
Fixed in https://github.com/FlashyReese/reeses-sodium-options/commit/c6bb5b97e9314bf7ac0d5129cab9fee0804aa5f4. You can try the latest release.
