### ISSUE TITLE
{BUG} [Low Priority] Strikethrough Renders over Description Box

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [FlashyReese/reeses-sodium-options#26]
## Description

The strikethrough is rendered over the description box when hovering over an option.

## Steps to Reproduce

1. Launch Minecraft with Sodium on Windows 10
2. Open "Options"
3. Open "Video Settings"
4. Open "Extras"
5. Hover cursor over "Use Fast Random"
6. The strikethrough from "Reduce Resolution on macOS" should render over the description for "Use Fast Random"

## Screenshots

![strikethrough1](https://user-images.githubusercontent.com/69123018/146966368-731b79de-3a44-4153-bc6b-94c3937edfa2.jpg)
![strikethrough2](https://user-images.githubusercontent.com/69123018/146966366-9144d6b2-f063-4e50-bb09-a94038a5c507.jpg)

### Java Version

AdoptOpenJDK jdk-16.0.1.9-hotspot

### Sodium Version

mc1.17.1-0.3.3+build.8

### Mod Version

mc1.17.1-1.2.3

### CPU

AMD Ryzen 3 2200G with Radeon Vega Graphics

### GPU

AMD Radeon(TM) Vega 8 Graphics

## Additional Info

I am using the Fabulously Optimized modpack, version 2.6.1 for 1.17.

**Comment by FlashyReese** [comment]
I have looked through this issue before, sadly there is nothing I can do to fix this. Vanilla renders the strikethrough line after everything else is rendered on the screen.

**Comment by BeansBeefBroccoli** [comment]
Ok, thanks for checking!
