### ISSUE TITLE
Should use the new Iris API in Iris 1.1.4, instead of depending on Iris internals

### ISSUE THREAD

**Issue by coderbot16** [FlashyReese/reeses-sodium-options#27]
The Iris API isn't distributed separately yet, but it has a much better stability guarantee than reflecting into internal Iris classes. In the future we plan to do reorganization and repackaging which might break things in your mod.

The following two methods should be sufficient: https://github.com/IrisShaders/Iris/blob/41721a53dde15698bf03c6763475c62978105e7c/src/main/java/net/irisshaders/iris/api/v0/IrisApi.java#L64-L90

Ideally, this change could be backported to 1.16.5 and 1.17.1, but I understand if you do not wish to do that.

**Comment by FlashyReese** [comment]
Thank you, I will use the new API and also backport it to previous versions.

**Comment by coderbot16** [comment]
Great, thanks! I'll make sure to tag future versions of Iris to run with the latest versions of this mod for each MC version to avoid any potential issues with versions mismatches once we do choose to do any internal refactoring / repackaging.

**Comment by FlashyReese** [comment]
I have released `1.3.0` with the new Iris API changes. I've also included a break clause to prevent users from loading versions prior to `Iris 1.1.4`. Thanks for providing an API to avoid any issues in the future.
