### ISSUE TITLE
[Incompatibility] sodium-shadowy-path-blocks

### ISSUE THREAD

**Issue by NaiNonTH** [FlashyReese/reeses-sodium-options#31]
### Description
The Game Crashed whilst clicking the 'Video Settings' option.

### Brief Crashed report
```
The game crashed whilst mouseclicked event handler
Error: java.lang.RuntimeException: Mixin transformation of me.flashyreese.mods.reeses_sodium_options.client.gui.SodiumVideoOptionsScreen failed
Exit Code: -1
```

### Full Crashed report
[crash-2022-03-10_21.04.58-client.txt](https://github.com/FlashyReese/reeses-sodium-options/files/8224012/crash-2022-03-10_21.04.58-client.txt)

**Comment by NaiNonTH** [comment]
### Additional Info
The issue started after I've installed FabrikMC and Fabric Language Kotlin mod. Not so sure if that's the cause.

**Comment by FlashyReese** [comment]
It's an incompatibility with https://github.com/Rynnavinx/sodium-shadowy-path-blocks/issues/6

**Comment by FlashyReese** [comment]
The issue most be resolved on Rynnavinx's end.

**Comment by FlashyReese** [comment]
Resolved with https://github.com/Rynnavinx/sodium-shadowy-path-blocks/commit/e5646a19190405f612af8bec50e332f03121c3f4
