### ISSUE TITLE
Buttons are doubled.

### ISSUE THREAD

**Issue by wd4q5dy** [FlashyReese/reeses-sodium-options#32]
there are two of each of the buttons for the [Sodium Extra](https://www.curseforge.com/minecraft/mc-mods/sodium-extra) mod and I can't figure out why
<img width="1440" alt="bug" src="https://user-images.githubusercontent.com/78885219/158055413-41453ab8-1ae9-4cb2-983e-3c9c336ef451.png">

**Comment by wd4q5dy** [comment]
plus I forgot to mention they function properly and are the same stuff

**Comment by FlashyReese** [comment]
What version of Sodium Extra and RSO are you running? I did place a version lock for Sodium Extra to prevent this.

Edit: If you did remove this version lock manually then you shouldn't be reporting this issue.

**Comment by wd4q5dy** [comment]
it's 1.4.2 for RSO and 0.4.1 for Sodium Extra

Edit: I don't know what a version lock is

**Comment by wd4q5dy** [comment]
I'll download 0.4.2 and try

**Comment by wd4q5dy** [comment]
ahh that worked thanks
