### ISSUE TITLE
[Suggestion] Move the options in the center of the screen

### ISSUE THREAD

**Issue by RaptaG** [FlashyReese/reeses-sodium-options#33]
They are a little above the center (I circled the place I mean 😂)
![Screenshot_90](https://user-images.githubusercontent.com/77157639/160390720-2864a5cf-75c7-4eaa-98ae-a601bd09baa5.png)

**Comment by FlashyReese** [comment]
Ehm no, not happening :)

**Comment by RaptaG** [comment]
:C
