### ISSUE TITLE
Add support for GUI scale (screen scale) mod

### ISSUE THREAD

**Issue by EGOIST1372** [FlashyReese/reeses-sodium-options#37]
Add support for [GUI scale (screen scale)](https://www.curseforge.com/minecraft/mc-mods/tip-the-gui) mod

**Comment by FlashyReese** [comment]
I don't think I should be adding sliders for other mods into Sodium using this mod(Just restyles Sodium's menu). You would need the mod author to support Sodium's menu themselves.

**Comment by EGOIST1372** [comment]
it seems both mods are compatible, my bad :)
https://ibb.co/KK1wqDm
