### ISSUE TITLE
Main Menu options are unselectable in Fullscreen with mod installed

### ISSUE THREAD

**Issue by DartRuffian** [FlashyReese/reeses-sodium-options#38]
With the mod installed, I am unable to select any option on the main menu while in Fullscreen. No highlight appears, and clicking does nothing, requiring me to close the game, edit my options.txt to make the game run in windowed mode (by setting `fullscreen` to `false`), and then relaunch. The main menu works fine in windowed mode, and only fullscreen produces the issue.

**Comment by FlashyReese** [comment]
Are you running any other mods other than Sodium & Reese's Sodium Options? Reese's Sodium Options doesn't actually touch the main menu or full-screen controls, it only modifies the layout of the screen in Sodium video options.

**Comment by DartRuffian** [comment]
I am running other mods, but removing Reese's fixes it. To try and fix the problem, I tried unloading all of my mods, and adding each one individually and testing. Phosphor and Puzzle were both causing the issue. Puzzle creates an extra button, and disabling that button in the config resolved the issue.

**Comment by FlashyReese** [comment]
Can you provide the mod list that causes this issue? I assume it's `Sodium`, `Puzzle` and `Reese's Sodium Options`

**Comment by DartRuffian** [comment]
Relevant Mods
```
Sodium
Phosphor (Replaced with Starlight, does not cause the issue)
Puzzle (setting "enablePuzzleButton" to "false" in puzzle.json fixes it)
Reese's Sodium Options
```
[Full Modlist](https://pastebin.com/3rmP96e3)

**Comment by FlashyReese** [comment]
I can't seem to replicate your issue with the list of mods you provided. Do you have any relevant logs that you can upload? If not then this seems more of a Puzzle issue. As I mentioned previously Reese's Sodium Options doesn't actually touch fullscreen controls nor mess with the main menu.

Edit: Attached video for reference
https://user-images.githubusercontent.com/30311066/177904905-5bf3e270-68bd-4a3f-967b-8610d85353da.mp4
