### ISSUE TITLE
Options menu has a bug

### ISSUE THREAD

**Issue by DarkOleks** [FlashyReese/reeses-sodium-options#4]
When you go into Video settings, you can see only "General, Quality, etc" and click it, but other part(where is settings) is empty
<img width="1440" alt="Screen Shot 2021-08-08 at 11 19 03" src="https://user-images.githubusercontent.com/67630432/128625806-a171ad47-8376-4b7a-b130-c073919b5d79.png">

**Comment by FlashyReese** [comment]
If you are experiencing this on macOS. You can temporarily run [retiNO](https://www.curseforge.com/minecraft/mc-mods/retino) until a proper solution is integrated.
