### ISSUE TITLE
Option to style the buttons/menu as Minecraft-like

### ISSUE THREAD

**Issue by intergrav** [FlashyReese/reeses-sodium-options#40]
I couldn't find an issue that related to this, but sorry if I missed it

This isnt the best concept, but this is what I imagine it could kind of look like?

> I updated it because the original concept was really bad lol.
> 
> Something like this could work very well and would bring a big improvement to the look of the menu ![image](https://user-images.githubusercontent.com/42325132/183457922-66e5405b-d84a-42ea-851b-643e1959479f.png)

**Comment by linux-leo** [comment]
+1 from me

**Comment by intergrav** [comment]
I updated it because the original concept was really bad lol.

Something like this could work very well and would bring a big improvement to the look of the menu
![image](https://user-images.githubusercontent.com/42325132/183457922-66e5405b-d84a-42ea-851b-643e1959479f.png)

**Comment by FlashyReese** [comment]
Feel free to submit a PR, unless you did that with image editing.

**Comment by intergrav** [comment]
I did it with image editing, that was just a concept. I don't really know much about java haha

**Comment by FlashyReese** [comment]
![image](https://user-images.githubusercontent.com/30311066/183491734-b9a130b9-5877-41a5-88e2-70c99be2ad26.png)
This is the most cursed thing I've done

**Comment by FlashyReese** [comment]
![image](https://user-images.githubusercontent.com/30311066/183496139-00e30f56-01cc-44f7-acd7-1d39ce8c0ecb.png)
I'm still not sold on this idea

**Comment by intergrav** [comment]
Lmao I see what you mean, heres some things you could try to make it look better:
- Try adding shadows to the text
- Make the text a little smaller
- Add margin/padding to the buttons

**Comment by intergrav** [comment]
Maybe try adding increasing margin/padding between the buttons aswell

**Comment by intergrav** [comment]
Gonna close this as I'm not sure why I didn't before... yeah I agree this looks quite cursed. Not sure what I was thinking lmao

**Comment by FlashyReese** [comment]
Well alternatively, https://github.com/isXander/xanders-sodium-options/
