### ISSUE TITLE
Accessibility Support

### ISSUE THREAD

**Issue by FlashyReese** [FlashyReese/reeses-sodium-options#46]
Sodium's options framework doesn't support navigation and narration.

**Comment by Madis0** [comment]
Navigation exists as of 1.19.4, but should be improved as this mod hinders it a bit. 

- Open the video settings and try to navigate to "Done" button with the keyboard. Then try to navigate back - can't. Why? The original screen allows that.
- Similarly, "left" and "right" are switched for navigating tabs.
- Edit: On the positive side, it is possible to adjust the options themselves at all, which is not possible on the original screen. Also, everything can be navigated back and forth with some use of the Tab key, which is - again - unlike the default Sodium options.

**Comment by FlashyReese** [comment]
Resolved with https://github.com/FlashyReese/reeses-sodium-options/commit/7d3cb0e6f3a07c27989028612ef41421c8ed063f and in release `1.6.1`.
