### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by mystriii** [FlashyReese/reeses-sodium-options#47]
After moving .jar file into folder, the modified menu does not appear. The mod appears under Sodium in the menu from 'Mod Menu' however. I'm on 1.19.2 using the latest versions of sodium fabric and reeses options. On Mac Catalina

**Comment by FlashyReese** [comment]
Can you provide a screenshot and a log file?

Edit:
Log file is located in `.minecraft/latest.log`

**Comment by mystriii** [comment]
What is a log file and how do I retrieve it? Here I have put 2 screenshots
one is reese's options installed as seen in mod menu, and the other is my
video settings not having the expanded reese options. Thanks!

**Comment by FlashyReese** [comment]
You would need to reply directly on the GitHub issue you created, emailing won't forward any attachments.

**Comment by mystriii** [comment]
Hi apologies, here are the two screenshots. As mentioned, one is just showing that Reese's options is installed and the other is showing that my video settings are not the reese's ones. Thanks btw! :)
<img width="848" alt="Screen Shot 2022-10-10 at 2 40 47 PM" src="https://user-images.githubusercontent.com/115446079/195085566-9f10ecdc-e8ea-450c-9a71-5ecd3e104c22.png">
<img width="1680" alt="Screen Shot 2022-10-10 at 2 38 59 PM" src="https://user-images.githubusercontent.com/115446079/195085575-7a668f16-3cfb-43d3-b39d-42b8bd70234d.png">

**Comment by FlashyReese** [comment]
Hello, the screenshots you shared show that the mod is working correctly.

Sodium Default
![image](https://user-images.githubusercontent.com/30311066/195196526-050ded11-f2be-45a7-8e79-cbb10561e00b.png)

Reese's Sodium Options
![image](https://user-images.githubusercontent.com/30311066/195195637-c03cde17-d024-42cc-b170-478d21036402.png)

Unless you are looking for [Sodium Extra](https://www.curseforge.com/minecraft/mc-mods/sodium-extra).

**Comment by mystriii** [comment]
Thank you! That is exactly what I was looking for.

**Comment by FlashyReese** [comment]
No problem :P
