### ISSUE TITLE
What does this even do?

### ISSUE THREAD

**Issue by itsdinkd** [FlashyReese/reeses-sodium-options#5]
No description anywhere what this actually does/add

**Comment by PeterTheSalmon** [comment]
It's a test to see if the mac video settings bug would still be present in different cases, i.e. without sodium extra's options, and just with standard sodium.

**Comment by FlashyReese** [comment]
It's a small mod that changes the layout of the Sodium Video Options Screen to my preferred layout, some people do prefer this layout over the original one. Hence this is why I'm releasing it as a mod, it was only initially bundled with Sodium Extra for testing.
