### ISSUE TITLE
Search Bar for Particles when using Sodium Extra

### ISSUE THREAD

**Issue by Avakining** [FlashyReese/reeses-sodium-options#51]
When playing a big mod pack there can be thousands of different particles, making it difficult to find the exact one you want to disable. Some way of searching or filtering (by mod that added it and/or name of the particle) would be greatly appreciated.

I was referred to suggest this feature in a Sodium UI mod in [the issue](https://github.com/FlashyReese/sodium-extra-fabric/issues/303) I made under Sodium Extra.

**Comment by JLUsr** [comment]
> I was referred to suggest this feature in a Sodium UI mod in the issue I made under Sodium Extra.

I think this is a bit of a misunderstanding. _Sodium Extra_ and _Reese's Sodium Options_ are both by FlashyReese. You will most likely get the same reply here as you did in the other issue you posted. _Reese's Sodium Options_ is using the default Sodium UI, it is essentially just improving the existing user experience as it says on CurseForge and Modrinth, "Replaces Sodium's Options Screen with intention of improving UX".

If you don't want to use [Xander's Sodium Options](https://github.com/isXander/xanders-sodium-options/) and just want to use the default Sodium UI ~~you should consider making this request [here](https://github.com/CaffeineMC/sodium-/issues)~~ then you might just be out of luck.

**Comment by FlashyReese** [comment]
I would not open an issue on Sodium issue tracker because their video screen is not meant to be mixin into.

**Comment by FlashyReese** [comment]
Implemented in `1.6.0`
