### ISSUE TITLE
Incorrect tooltip rendering (1.20.1)

### ISSUE THREAD

**Issue by spunchbop121** [FlashyReese/reeses-sodium-options#53]
https://ibb.co/fYWmJwy

https://ibb.co/XxvK4g9

Mod list:
chat_heads-0.10.15-fabric-1.20
cloth-config-11.0.99-fabric
fabric-api-0.83.1+1.20.1
modmenu-7.0.1
reeses_sodium_options-1.5.0+mc1.20-build.73
sodium-extra-0.4.20+mc1.20-build.103
sodium-fabric-mc1.20-0.4.10+build.27
suggestion-tweaker-1.20-1.4.2-fabric

**Comment by FlashyReese** [comment]
Please update to this version, https://modrinth.com/mod/reeses-sodium-options/version/mc1.20-1.5.1
