### ISSUE TITLE
Search bar partially overlaps "Shader Pack" button (version 1.6.x)

### ISSUE THREAD

**Issue by raspberrygitq** [FlashyReese/reeses-sodium-options#56]
### What are we supposed to do?

Install the latest version of **Fabric 0.14.21**
Version: **1.16.5, 1.17.1, 1.18.2, 1.19-1.19.3, 1.19.4, 1.20-1.20.1**

### The following mods:

Sodium
Iris
reeses-sodium-options (latest version 1.6.x) (1.16.5, 1.17.1, 1.18.2, 1.19-1.19.3, 1.19.4, 1.20-1.20.1)

### Screenshot's:

- **1.16.5** 

![2023-07-26 151556](https://github.com/FlashyReese/reeses-sodium-options/assets/90698953/bb9f0a0f-b217-4e63-b885-ff21909350ee)

- **1.17.1** 

![2023-07-26 151311](https://github.com/FlashyReese/reeses-sodium-options/assets/90698953/b1fd9e5b-98ee-42e5-9fd0-14c733e87e84)

- **1.18.2** 

![2023-07-26 152001](https://github.com/FlashyReese/reeses-sodium-options/assets/90698953/ef9f8334-76df-49c8-998b-1030c4e7bbe0)

- **1.19-1.19.3** 

![2023-07-26 153503](https://github.com/FlashyReese/reeses-sodium-options/assets/90698953/d484ec2c-5c80-4bf0-85b0-8b27cc8b84f6)

- **1.19.4**

![2023-07-26 153846](https://github.com/FlashyReese/reeses-sodium-options/assets/90698953/702a4961-1079-49aa-bca6-71b976f9769b)

- **1.20-1.20.1**

![2023-07-26 154117](https://github.com/FlashyReese/reeses-sodium-options/assets/90698953/304a0b1a-fc46-4a52-954a-a46b3313c6ff)

**Comment by FlashyReese** [comment]
This is now fixed in `1.6.3`
