### ISSUE TITLE
No text in search box (only 1.19-1.19.3)

### ISSUE THREAD

**Issue by raspberrygitq** [FlashyReese/reeses-sodium-options#57]
### What are we supposed to do?

Install the latest version Fabric 0.14.21
Version: **1.19-1.19.3**

### Mod version where is the error:

- reeses_sodium_options-1.6.3+mc1.19.2-build.89

### Screenshot

- On the left is version **1.18.2** where text is displayed normally, and on the right **1.19.2** there is no text in the search bar

![Screenshot_4](https://github.com/FlashyReese/reeses-sodium-options/assets/90698953/a2b71a68-18f7-4d05-8989-441af775d9d7)

**Comment by FlashyReese** [comment]
It seems that I actually missed cherry-picking that commit for 1.19.2. This will be fixed in the next release, whenever it comes. Since it's not crucial and does not affect the functionality, I won't make an immediate release now.

**Comment by FlashyReese** [comment]
Made a patch for it, this is slightly bothering me when playing AOF6. Fixed in `1.6.4`.
