### ISSUE TITLE
Crashes upon clicking into video options

### ISSUE THREAD

**Issue by AchievedZeus574** [FlashyReese/reeses-sodium-options#66]
Tested mixing different mods in and out, only occurs with Sodium Options enabled. 
[crash-2023-08-13_19.09.47-client.txt](https://github.com/FlashyReese/reeses-sodium-options/files/12330723/crash-2023-08-13_19.09.47-client.txt)

Mod list
```
AppleSkin
Better Statistics 
Borderless Mining
Controlling
Custom Crosshair
Enchantment Descriptions
Essential Mod
Inventory+
Iris Shaders
Jade
Journey Map
Mouse Tweaks
Reese's Sodium Options
REI
Searchables
Sodium
Sodium Extra
TPS Hud
``` 
All mods updated to latest versions

**Comment by FlashyReese** [comment]
You didn't update RSO to the latest version, your log says `1.6.3+1.20.1` and the latest version is `1.6.4+1.20.1`. You can fidn it here: https://modrinth.com/mod/reeses-sodium-options/version/mc1.20.1-1.6.4
