### ISSUE TITLE
Add quilt and sodium 0.5.2 support

### ISSUE THREAD

**Issue by unatried** [FlashyReese/reeses-sodium-options#67]
@FlashyReese could you please add Sodium 0.5.2 and Quilt support for both Sodium Extra and Reeses Sodium Options
I know that you can compile sodium extra for sodium 0.5.2 by doing "git clone https://github.com/ZugCodez/sodium-extra-fabric.git -b 1.20.x/dev-1" then "cd sodium-extra-fabric” and then "gradle build" but there is no version on modrinth curseforge or github for direct download that would make it easier for everyone people and there are some conflicts that i can not join the game

**Comment by Julienraptor01** [comment]
The latest are compatible with sodium 0.5.2, there's no need for an update as shown by this https://github.com/FlashyReese/sodium-extra-fabric/pull/356#issuecomment-1683520488
\+ it should be compatible with quilt whitout any change

**Comment by unatried** [comment]
Even Reese's sodium options works with sodium 0.5.2!? Because it didn't for me.
