### ISSUE TITLE
Crash when clicked the 'Video settings' button

### ISSUE THREAD

**Issue by SnowCutieOwO** [FlashyReese/reeses-sodium-options#73]
This is the crash report:
https://mclo.gs/yIgWD2C

More details could be added if anyone asked.
Thanks!

**Comment by FlashyReese** [comment]
You are running `1.20.2` version of the mod on `1.20.1`.
![image](https://github.com/FlashyReese/reeses-sodium-options/assets/30311066/15f6d0f2-8a7c-4c29-936c-ef75ebb7dfd7)

**Comment by MrcrystalXD** [comment]
how to fix this issue
