### ISSUE TITLE
Please add Sodium 0.5.3 support in 1.20.1 release

### ISSUE THREAD

**Issue by alexweber** [FlashyReese/reeses-sodium-options#74]
The latest Sodium 0.5.3 release supports 1.20.1 however this mod and SE only support 0.5.3 in the 1.20.2 branch, could we please get it backported to 1.20.1 as a final release for partity with Sodium/Iris/Indium which are all on 0.5.3 for 1.20.1....  thanks!!

**Comment by FlashyReese** [comment]
[SE 0.5.1](https://modrinth.com/mod/sodium-extra/version/mc1.20.1-0.5.1) is compatible with Sodium 0.5.3 for 1.20.1
