### ISSUE TITLE
Crash on Minecraft opening

### ISSUE THREAD

**Issue by tevenweven** [FlashyReese/reeses-sodium-options#77]
When I attempt to load the game it crashes saying:
```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'Minecraft' (minecraft) 1.20.4 with any 1.18.x version.
More details:
	 - Mod 'Reese's Sodium Options' (reeses-sodium-options) 1.7.0+mc1.20.2-build.97 requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
I have the 1.20.4 version of Reese's Sodium Options (or, I should, it's what clicked on for the download on Modrinth, and have clicked on when I tried again just in case) and Sodium but it says I need 1.18.x. This happens with many mods and with a just a few, with and without Sodium Extra and has happened on multiple machines and installs of Windows 10. It also has happened through many different versions of the mods and Minecraft and has never seemed to have been fixed.

**Comment by FlashyReese** [comment]
Sorry for the late response, I was away for a couple of months. You might have a dependency override in your configs probably left by a modpack. You can delete `.minecraft/config/fabric_loader_dependencies.json` to resolve this issue.
