### ISSUE TITLE
Scrolling issue with "more culling" mod

### ISSUE THREAD

**Issue by Werwolf257** [FlashyReese/reeses-sodium-options#85]
When having the "more culling" mod installed and scrolling on this section, there is an apparent issue. When scrolling down in this menu all the boxes where you can eiter check to enable, or uncheck to disable settings scroll along, as they should. However the 3 slider options in this menu, when scrolling down just stay in place, and are overlapping with other options. I dont know if reporting this here is the right thing, or if it is an issue on the side of the "more culling" mod
![scrolled down](https://github.com/FlashyReese/reeses-sodium-options/assets/88732454/22f22774-efdf-4d94-a72b-dfdf91b61ed8)
![not scrolled down](https://github.com/FlashyReese/reeses-sodium-options/assets/88732454/a602479f-8ea7-4589-ba43-396d61e02d42)

**Comment by ghost** [comment]
I am having the same issue. Certain numbers remain in the same location when scrolling, causing overlapping text.

**Comment by TheRealDanini** [comment]
+1 quilt on minecraft 1.20.4
I have not noticed this on previous versions of minecraft

Reese's Sodium Options ver 1.7.2
MoreCulling ver 0.24.0
Quilt loader ver 0.25.0

**Comment by librepo-dev** [comment]
Still not fixed on Fabric 1.20.6 with reese 1.7.2

**Comment by Franco227** [comment]
Can confirm on Minecraft 1.21

Reese's Sodium Options 1.8.0-beta.2
MoreCulling 0.27.1
Fabric Loader 0.16.5

**Comment by Franco227** [comment]
This is fixed in MoreCulling's latest release.

**Comment by flikrheist** [comment]
https://github.com/FlashyReese/reeses-sodium-options/issues/112
