### ISSUE TITLE
opening options menu crashed game

### ISSUE THREAD

**Issue by Waddly7** [FlashyReese/reeses-sodium-options#87]
https://bytebin.lucko.me/av2OphvLJc

**Comment by makumaku1974** [comment]
same same haha

**Comment by FlashyReese** [comment]
Sorry for the late response, I was away from a couple of months. The link seems to be expired. Please upload the log itself or use our Discord's support forum

**Comment by makumaku1974** [comment]
this is fixed i think on 1.21

**Comment by seriousfreezing** [comment]
Not fixed in 1.21.1

**Comment by FlashyReese** [comment]
Can't assist you without a log or a crashlog

> Not fixed in 1.21.1

**Comment by luciobortoletto** [comment]
> Can't assist you without a log or a crashlog
> 
> > Not fixed in 1.21.1

I'm having the same issue, here is the crash report: https://mclo.gs/6YcOoi4. I'm on 1.21.1 fabric 0.16.3 with other mods. The version of Reese's Sodium Options is mc1.21.1-1.8.0-beta.2+fabric

**Comment by Rheydskey** [comment]
I have a crash too when opening option's menu in 1.21.1 with modpack [Fabulously Optimized](https://github.com/Fabulously-Optimized/fabulously-optimized)
Here a crashlog.
[crash-2024-08-27_12.12.14-client.txt](https://github.com/user-attachments/files/16760464/crash-2024-08-27_12.12.14-client.txt)

**Comment by FlashyReese** [comment]
> I have a crash too when opening option's menu in 1.21.1 with modpack [Fabulously Optimized](https://github.com/Fabulously-Optimized/fabulously-optimized)
> 
> Here a crashlog.
> 
> [crash-2024-08-27_12.12.14-client.txt](https://github.com/user-attachments/files/16760464/crash-2024-08-27_12.12.14-client.txt)
> 
> 

https://github.com/FlashyReese/reeses-sodium-options/issues/98#issuecomment-2308722165
