### ISSUE TITLE
"Mod embeddium only supports 'textrues_embeddium_options' 0.0.0-NOT-COMPATABLE     Currently, 'textrues_embeddium_options' is 0.1.5+mc1.20.1"

### ISSUE THREAD

**Issue by LunarAnticGitHub** [FlashyReese/reeses-sodium-options#88]
![Screenshot (807)](https://github.com/FlashyReese/reeses-sodium-options/assets/131813123/ea0e0136-17a1-493c-9327-4e2304f673a1)

Modpack will not boot past this point

**Comment by LunarAnticGitHub** [comment]
This is on minecraft v1.20.1, forge v47.2.30

**Comment by FlashyReese** [comment]
I believe you are asking on the wrong repository issue tracker. This mod doesn't have an official Forge port. https://github.com/ThinkingStudios/textrues-embeddium-options

**Comment by TexBlock** [comment]
@LunarAnticGitHub 

see https://github.com/ThinkingStudios/textrues-embeddium-options/issues/9

**Comment by Kondr654321** [comment]
а чё делать?
