### ISSUE TITLE
Incompatibility with FancyMenu

### ISSUE THREAD

**Issue by seriousfreezing** [FlashyReese/reeses-sodium-options#90]
I tried to make a button that goes to the Reese's Sodium Options interface, but it doesn't seem to be working. Any suggestions?

**Comment by seriousfreezing** [comment]
Sorry, my mistake. I meant whether it will support FancyMenu. Like Sodium itself doesn't have the compatibility to make a button to go to the graphics settings screen (and I don't know what the current status of this is in Sodium) While Reese's makes it into another graphics page and I was wondering if it would have something like that for this mod.

**Comment by FlashyReese** [comment]
Fixed in https://github.com/FlashyReese/reeses-sodium-options/commit/d9bca57d95b3b36e52e50cf9e9804146baf69856
