### ISSUE TITLE
1.8.0 beta1 crashes when clicking on "Video settings"

### ISSUE THREAD

**Issue by Longie520** [FlashyReese/reeses-sodium-options#98]
Game version: 1.21.1
Java version: bundled ARM64 Java 21.0.3
Fabric version: 0.16.2
Hardware: M1 MacBook pro

To reproduce:
1. Install latest FAPI, Sodium, Sodium Extra + Reese's Sodium Options and launch
2. Go to Options > Video settings
3. Upon clicking "Video settings" the game crashes.

Here are the log and crash report
[latest.log](https://github.com/user-attachments/files/16734760/latest.log)
[crash-2024-08-24_10.33.53-client.txt](https://github.com/user-attachments/files/16734761/crash-2024-08-24_10.33.53-client.txt)

**Comment by SynergyShadow** [comment]
getting the same crash when clicking on video settings


[crash-2024-08-23_21.26.20-client.txt](https://github.com/user-attachments/files/16734798/crash-2024-08-23_21.26.20-client.txt)

**Comment by Hippopipo** [comment]
@FlashyReese still getting this crash after newest update
https://mclo.gs/4vXqYDc

**Comment by FlashyReese** [comment]
> @FlashyReese still getting this crash after newest update
> 
> https://mclo.gs/4vXqYDc

This is caused by Controlify they are mixing into our mod (old version of it)
